### ISSUE TITLE
500 Error on exapp installation

### ISSUE THREAD

**Issue by lainlives** [cloud-py-api/app_api#309]
### Describe the bug

I have the socket docker installed and it can ping it but thats it.  Everything else fails 0/6 on deployment test.

### Steps/Code to Reproduce

Follow official guide to configure appapi. 
Install exapp.

### Expected Results

Exapps install properly

### Actual Results

AxiosError", … }
​​
code: "ERR_BAD_RESPONSE"
​​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​​
message: "Request failed with status code 500"
​​
name: "AxiosError"
​​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​
response: Object { data: {…}, status: 500, statusText: "Internal Server Error", … }
​​
stack: "r@https://XXhostmachineXX/apps/app_api/js/app_api-main.js?v=fa70b74f-27:2:3637979\nr@https://XXhostmachineXX/apps/app_api/js/app_api-main.js?v=fa70b74f-27:2:3644810\nC@https://XXhostmachineXX/apps/app_api/js/app_api-main.js?v=fa70b74f-27:2:3631985\n"
​​
<prototype>: Object { constructor: r(e, t, n, a, r), toJSON: toJSON(), stack: "", … }

### Setup configuration

Nextcloud 29.0.2.2
Current appapi from the appstore.
Ubuntu 22.04.4 LTS

**Comment by andrey18106** [comment]
@lainlives Could you please describe your setup so that we can understand which part is wrong and help?

**Comment by aef5748** [comment]
I got the same problem
![Screenshot from 2024-08-01 13-59-46](https://github.com/user-attachments/assets/ce966600-9b87-4be8-b144-815538671f85)

my config as below:
AppApi
![Screenshot from 2024-08-01 13-57-13](https://github.com/user-attachments/assets/b039c0a4-1c85-4b15-8bf6-4a0ee46c1c78)
docker-compose.yml
```
version: '3.7'
networks:
  nextcloud:
    name: nextcloud_proxy
    driver: bridge
    
volumes:
  nexecloud:
  db:
  appapi:

services:
  db:
    image: postgres:12-alpine
    container_name: Nextcloud-DB
    restart: always
    volumes:
      - /home/sw/Nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - TZ=Asia/Taipei
    networks:
      - nextcloud

  els:
    image: elasticsearch:8.14.1
    container_name: Nextcloud-elasticsearch
    restart: always
    volumes:
      - /home/sw/Nextcloud/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/sw/Nextcloud/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      - node.name=nextcloud
      - cluster.name=nextcloud
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_POTS=-Xms512m -Xmx512m
      - TZ=Asia/Taipei
      - bootstrap.memory_lock=true
      - ELASTIC_CONTAINER=true
      - FULLTEXTSEARCH_PASSWORD=nextcloud
      - logger.org.elasticsearch.discovery=WARN
      - xpack.license.self_generated.type=basic
    ports:
      - 9200:9200
    networks:
      - nextcloud

  app:
    image: crd/nextcloud:29.0.3-apache
    container_name: Nextcloud
    restart: always
    ports:
      - 3000:80
    depends_on:
      - db
      - appapi
      - els
    links:
      - db
      - els
      - appapi
    volumes:
      - /home/sw/Nextcloud/web:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    networks:
      - nextcloud
      
  appapi:
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:v1.3.2
    container_name: nextcloud-appapi-dsp
    hostname: nextcloud-appapi-dsp
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NC_HAPROXY_PASSWORD=nextcloud
      - TIMEOUT_SERVER=1800s
    networks:
      - nextcloud
```
