### ISSUE TITLE
Failed to open stream: connection timed out, when use docker behind company proxy.

### ISSUE THREAD

**Issue by aef5748** [cloud-py-api/app_api#364]
My nextcloud is setup on the docker behind company proxy.
After installed app_api then try to test_deploy, but got the following message:
```
file_get_contents(https://raw.githubusercontent.com/cloud-py-api/test-deploy/main/appinfo/info.xml): Failed to open stream: Connection timed out at /var/www/html/custom_apps/app_api/lib/Service/ExAppService.php#277
```
Use Nextcloud to download others app successfully, so I think the network is workable.
How can I solved it?

NC: 29.0.3-apache
Appapi: 3.1.0

**Comment by bigcat88** [comment]
Hello, sorry for the delay in replying.

If we can figure out how we can easily reproduce this in dev setups, then we can answer.
Are there any steps, what proxy should we set and how to configure it - what should we try?

**Comment by aef5748** [comment]
Deployment Steps:
1. Deploy Nextcloud using Docker on a company network that has a proxy server.
2. After configuring the proxy server authentication in Docker, reload the configuration file and restart Docker.

<details>
<summary>/etc/systemd/system/docker.service.d/http-proxy.conf</summary>

```
[Service]
Environment="HTTP_PROXY=http://username:password@proxy.company.com:3128"
Environment="HTTPS_PROXY=http://username:password@proxy.company.com:3128"
Environment="NO_PROXY=localhost,127.0.0.0/8,docker-registry.company.com"
```

</details>

4. Set up the proxy server authentication in the docker-compose file to deploy Nextcloud, and update the certificates in the Nextcloud container to the company certificates, then restart the container.

<details>
<summary>docker-compose.yaml</summary>

```
version: '3.7'
networks:
  nextcloud:
    name: nextcloud_proxy
    driver: bridge
    
volumes:
  nexecloud:
  db:
  appapi:

services:
  db:
    image: postgres:12-alpine
    container_name: Nextcloud-DB
    restart: always
    volumes:
      - /home/sw/Nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - TZ=Asia/Taipei
    networks:
      - nextcloud

  app:
    image: nextcloud:29.0.3-apache
    container_name: Nextcloud
    restart: always
    ports:
      - 3000:80
    depends_on:
      - db
      - appapi
    links:
      - db
      - appapi
    volumes:
      - /home/sw/Nextcloud/web:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - HTTP_PROXY=http://username:password@proxy.company.com:3128
      - HTTPS_PROXY=http://username:password@proxy.company.com:3128
      - NO_PROXY=localhost,127.0.0.0/8,docker-registry.company.com 
    networks:
      - nextcloud
      
  appapi:
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
    container_name: nextcloud-appapi-dsp
    hostname: nextcloud-appapi-dsp
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NC_HAPROXY_PASSWORD=nextcloud
      - TIMEOUT_SERVER=1800s
      - TIMEOUT_CONNECT=180s
      - TIMEOUT_CLIENT=180s
    ports:
      - 127.0.0.1:2375:2375
    networks:
      - nextcloud
```

</details>

6. Download and install the appapi through the Nextcloud apps.
7. After configuring the relevant parameters for appapi, click on "Test_deploy"

<details>
<summary>appapi config</summary>

```
ExApps installed: 1
Name: docker_socket_proxy
Protocol: http
Host: nextcloud-appapi-dsp:2375
 
Deploy config
Docker network: nextcloud_proxy
Nextcloud URL: http://192.168.101. 20:3000
HaProxy password: nextcloud
GPUs support: true
Compute device: CUDA
```

</details>

After setting up according to the steps above, an error message pops up.
```
file_get_contents(https://raw.githubusercontent.com/cloud-py-api/test-deploy/main/appinfo/info.xml): Failed to open stream: Connection timed out at /var/www/html/custom_apps/app_api/lib/Service/ExAppService.php#277 
```

I have also tried to manually execute the app registration, but there is a similar error message.
```
php occ app_api:app:register --force-scopes test-deploy docker_socket_proxy --info-xml https://raw.githubusercontent.com/cloud-py-api/test-deploy/main/appinfo/info.xml --test-deploy-mode --no-ansi --no-warnings
```

I tried downloading the info.xml of test_deploy and specifying it directly, which can successfully register, but an error occurs when downloading the test_deploy image.
Command:
```
php occ app_api:app:register --force-scopes test-deploy docker_socket_proxy --info-xml /var/www/html/info.xml --test-deploy-mode --no-ansi --no-warnings
```
Error message:
```
Failed to pull image, GuzzleException occur: Server error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fcloud-py-api%2Ftest-deploy%3Arelease` resulted in a `504 Gateway Time-out` response 
```
